Return output path
gregchapman-dev/musicdiff pull request #1
Opened 2022-01-25 12:33 UTC by fosfrancesco

Three contributions:

1. Added support for saving the pdfs in a specific location.
2. Added a colab notebook for very easy online usage
3. Added specific error printing if music21 can't parse a score

2022-01-25 21:11 UTC, gregchapman-dev requested changes

2022-01-25 21:11 UTC, gregchapman-dev commented on musicdiff/__init__.py
> +                print(e)
print(e, file=sys.stderr)
... so that apps whose primary output is stdout don't get these errors intermingled.

2022-01-25 21:11 UTC, gregchapman-dev commented on musicdiff/__init__.py
> +                print(e)
print(e, file=sys.stderr)
... so that apps whose primary output is stdout don't get these errors intermingled.

2022-01-25 21:11 UTC, gregchapman-dev commented on musicdiff/visualization.py
> +            score1.write("musicxml.pdf", fp=out_path1)
makeNotation=False
(otherwise music21 will run through the score, changing all sorts of stuff before doing the export)

2022-01-25 21:11 UTC, gregchapman-dev commented on musicdiff/visualization.py
> +            score2.write("musicxml.pdf", fp=out_path2)
makeNotation=False
(otherwise music21 will run through the score, changing all sorts of stuff before doing the export)

2022-01-25 21:11 UTC, gregchapman-dev commented on examples/musicdiff_demo.ipynb
> +{
The amount of data here that is specific to your run of this colab is distressing.  I don't know much about colab; is that extra output here supposed to be committed?

2022-01-25 21:11 UTC, gregchapman-dev commented on examples/musicdiff_demo.ipynb
> +      "outputs": [
All these outputs are not here for the benefit of anyone using this colab.  Can they be removed somehow?

2022-01-25 21:11 UTC, gregchapman-dev commented on examples/musicdiff_demo.ipynb
> +      "outputs": [
More outputs that don't seem relevant.

2022-01-25 21:11 UTC, gregchapman-dev commented on examples/musicdiff_demo.ipynb
> +      "outputs": [
More outputs that aren't necessary (I hope).

2022-01-25 21:11 UTC, gregchapman-dev commented on examples/musicdiff_demo.ipynb
> +      "outputs": [
More outputs...

2022-01-25 21:11 UTC, gregchapman-dev commented on examples/musicdiff_demo.ipynb
> +      "outputs": [
More outputs...

2022-01-25 21:11 UTC, gregchapman-dev commented on examples/musicdiff_demo.ipynb
> +      "outputs": [
More outputs...

2022-01-26 11:10 UTC, fosfrancesco commented
All valid points! I changed all the parts you asked

2022-01-26 18:30 UTC, gregchapman-dev approved these changes
Looks good!  Thanks.

2022-01-26 18:34 UTC, gregchapman-dev commented
Squashed merge of pull request #1: add colab support, added support for saving the pdfs instead of displaying them, and improved error printing.

2022-01-26 18:42 UTC, gregchapman-dev commented
To https://github.com/gregchapman-dev/musicdiff.git
   5109b20..1916cd7  main -> main

2022-01-26 18:42 UTC, closed without merging